### ISSUE TITLE
Ошибка при создании файла html-справки в папке doc

### ISSUE THREAD

**Issue by bardimnik** [znoxx/tbng#1]
Здравствуйте, при запуске команды make  в папке doc получаю вот такую ошибку:

pandoc -s --toc --toc-depth=4 --template=html5template 00-tbng_overview_RU.md 00_RU_metadata.yaml  -o 00-tbng_overview_RU.html 
make: pandoc: Команда не найдена
Makefile:10: ошибка выполнения рецепта для цели «00_RU»
make: *** [00_RU] Ошибка 127

pandoc установил. Как исправить данную ошибку?

**Comment by znoxx** [comment]
Ну у вас текст ошибки прям показывает:
"pandoc: Команда не найдена"
 добавьте исполняемый файл в PATH, чтобы система могла его найти
для начала вместо make просто наберите pandoc и увидите, что скорее всего система его не находит.

**Comment by bardimnik** [comment]
Да, Вы оказались правы. Спасибо Вам. Моя ошибка в том, что я установил pandoc с помощью pip, а надо было с помощью команды: sudo apt install pandoc.
После установки pandoc команда make отрабатывает без ошибок.
Спасибо Вам за помощь!
