### ISSUE TITLE
chkconfig error

### ISSUE THREAD

**Issue by miyalisya** [znoxx/tbng#13]
orangepi@orangepizero:~$ sudo tbng/engine/tbng.py chkconfig
Traceback (most recent call last):
  File "/home/orangepi/tbng/engine/tbng.py", line 569, in <module>
    main(args, loglevel)
  File "/home/orangepi/tbng/engine/tbng.py", line 33, in main
    runtime = json.load(data_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode)
orangepi@orangepizero:~$ npm -v
6.14.4
orangepi@orangepizero:~$ node -v
v14.0.0
orangepi@orangepizero:~$ cat ./tbng/config/tbng.json
{
  "cputemp": "default",
  "wan_interface": [
   {
     "name": "eth0"
   }
    ],
  "lan_interface": [
    {
      "name": "wlan0",
      "wireless": true
    }
  ],
  "allowed_ports_tcp" : [22,3000,7657,9050,8118,4200],
  "allowed_ports_udp" : [53],
  "lock_firewall": false
}

?

**Comment by znoxx** [comment]
1) Project is unsupported for now
2) Check with original file in conf dir first
3) Pure python failure on reading json file (again, check if it works with original version)
4) Looks you are not using armbian, but original distro from orangepi site. Not sure it is the root cause, but anyway :)
